#*
 * Copyright (C) 2014 Xillio (support@xillio.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *#
/* 
* Specification: If there is an error in the nested success block, this error MUST be thrown and the outer do block MAY catch this.
* Input: Error in inner Success block
* Expected: Outer success block is not triggered
*/

use Assert;

do {
	do {
		return;
	} success {
		Assert.error("Throw Error.");
	}
} success {
	Assert.error("Error in succes block should throw error.");
}

